In [7]:
import pandas as pd
df=pd.read_csv("train.csv")

In [9]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='object')

In [10]:
df.shape

(45593, 20)

In [11]:
df.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

In [12]:
df.describe

<bound method NDFrame.describe of             ID Delivery_person_ID Delivery_person_Age Delivery_person_Ratings  \
0      0x4607     INDORES13DEL02                   37                     4.9
1      0xb379     BANGRES18DEL02                   34                     4.5
2      0x5d6d     BANGRES19DEL01                   23                     4.4
3      0x7a6a    COIMBRES13DEL02                   38                     4.7
4      0x70a2     CHENRES12DEL01                   32                     4.6
...        ...                ...                 ...                     ...
45588  0x7c09      JAPRES04DEL01                   30                     4.8
45589  0xd641      AGRRES16DEL01                   21                     4.6
45590  0x4f8d     CHENRES08DEL03                   30                     4.9
45591  0x5eee    COIMBRES11DEL01                   20                     4.7
45592  0x5fb2   RANCHIRES09DEL02                   23                     4.9

       Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0                22.745049             75.892471                   22.765049
1                12.913041             77.683237                   13.043041
2                12.914264             77.678400                   12.924264
3                11.003669             76.976494                   11.053669
4                12.972793             80.249982                   13.012793
...                    ...                   ...                         ...
45588            26.902328             75.794257                   26.912328
45589             0.000000              0.000000                    0.070000
45590            13.022394             80.242439                   13.052394
45591            11.001753             76.986241                   11.041753
45592            23.351058             85.325731                   23.431058

       Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked  \
0                        75.912471  19-03-2022    11:30:00          11:45:00
1                        77.813237  25-03-2022    19:45:00          19:50:00
2                        77.688400  19-03-2022    08:30:00          08:45:00
3                        77.026494  05-04-2022    18:00:00          18:10:00
4                        80.289982  26-03-2022    13:30:00          13:45:00
...                            ...         ...         ...               ...
45588                    75.804257  24-03-2022    11:35:00          11:45:00
45589                     0.070000  16-02-2022    19:55:00          20:10:00
45590                    80.272439  11-03-2022    23:50:00          00:05:00
45591                    77.026241  07-03-2022    13:35:00          13:40:00
45592                    85.405731  02-03-2022    17:10:00          17:15:00

           Weatherconditions Road_traffic_density  Vehicle_condition  \
0           conditions Sunny                High                   2
1          conditions Stormy                 Jam                   2
2      conditions Sandstorms                 Low                   0
3           conditions Sunny              Medium                   0
4          conditions Cloudy                High                   1
...                      ...                  ...                ...
45588       conditions Windy                High                   1
45589       conditions Windy                 Jam                   0
45590      conditions Cloudy                 Low                   1
45591      conditions Cloudy                High                   0
45592         conditions Fog              Medium                   2

      Type_of_order Type_of_vehicle multiple_deliveries Festival  \
0            Snack      motorcycle                    0      No
1            Snack         scooter                    1      No
2           Drinks      motorcycle                    1      No
3           Buffet      motorcycle                    1      No
4            Snack         scooter                    1      No
...             ...             ...                 ...      ...
45588         Meal      motorcycle                    0      No
45589       Buffet      motorcycle                    1      No
45590       Drinks         scooter                    0      No
45591        Snack      motorcycle                    1      No
45592        Snack         scooter                    1      No

                 City Time_taken(min)
0              Urban         (min) 24
1      Metropolitian         (min) 33
2              Urban         (min) 26
3      Metropolitian         (min) 21
4      Metropolitian         (min) 30
...               ...             ...
45588  Metropolitian         (min) 32
45589  Metropolitian         (min) 36
45590  Metropolitian         (min) 16
45591  Metropolitian         (min) 26
45592  Metropolitian         (min) 36

[45593 rows x 20 columns]>

In [13]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [14]:
df.duplicated().sum
()

()

In [15]:
df.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

In [16]:
df['Delivery_person_Age'].unique()

array(['37', '34', '23', '38', '32', '22', '33', '35', '36', '21', '24',
       '29', '25', '31', '27', '26', '20', 'NaN ', '28', '39', '30', '15',
       '50'], dtype=object)

In [17]:
df['Delivery_person_Age'] = pd.to_numeric(
    df['Delivery_person_Age'],
    errors='coerce'
)

In [18]:
df['Delivery_person_Age'].dtype

dtype('float64')

In [19]:
df['Delivery_person_Age'].isnull().sum()

np.int64(1854)

In [20]:
df['Delivery_person_Age'].unique()

array([37., 34., 23., 38., 32., 22., 33., 35., 36., 21., 24., 29., 25.,
       31., 27., 26., 20., nan, 28., 39., 30., 15., 50.])

In [21]:
df['Delivery_person_Ratings'].unique()

array(['4.9', '4.5', '4.4', '4.7', '4.6', '4.8', '4.2', '4.3', '4', '4.1',
       '5', '3.5', 'NaN ', '3.8', '3.9', '3.7', '2.6', '2.5', '3.6',
       '3.1', '2.7', '1', '3.2', '3.3', '6', '3.4', '2.8', '2.9', '3'],
      dtype=object)

In [22]:
df['Delivery_person_Ratings'] = pd.to_numeric(
    df['Delivery_person_Ratings'],
    errors='coerce'
)

In [23]:
df['Delivery_person_Ratings'].unique()

array([4.9, 4.5, 4.4, 4.7, 4.6, 4.8, 4.2, 4.3, 4. , 4.1, 5. , 3.5, nan,
       3.8, 3.9, 3.7, 2.6, 2.5, 3.6, 3.1, 2.7, 1. , 3.2, 3.3, 6. , 3.4,
       2.8, 2.9, 3. ])

In [24]:
df['Delivery_person_Ratings'].isnull().sum()

np.int64(1908)

In [25]:
df[df['Delivery_person_Ratings'] > 5]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
3586,0x46d,BANGRES05DEL01,50.0,6.0,-12.970324,-77.645748,13.010324,77.685748,13-03-2022,NaN,12:30:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,(min) 25
4714,0x493,HYDRES17DEL01,50.0,6.0,-17.451976,-78.385883,17.561976,78.495883,04-04-2022,NaN,23:20:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,(min) 27
5169,0x4f2,JAPRES08DEL01,50.0,6.0,-26.910262,-75.783013,27.020262,75.893013,18-03-2022,NaN,18:50:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 20
5362,0x430,BANGRES19DEL01,50.0,6.0,12.914264,77.678400,13.024264,77.788400,06-04-2022,NaN,20:55:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Metropolitian,(min) 18
5651,0xbef1,AGRRES13DEL02,50.0,6.0,-27.159795,-78.042990,27.209795,78.092990,13-02-2022,NaN,18:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 20
6394,0x427,JAPRES06DEL02,50.0,6.0,26.911927,75.797282,27.041927,75.927282,02-04-2022,NaN,22:10:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,(min) 20
7031,0x3eb,MYSRES15DEL02,50.0,6.0,-12.352058,-76.606650,12.372058,76.626650,15-03-2022,NaN,10:00:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,(min) 14
7681,0xd42,VADRES09DEL01,50.0,6.0,0.000000,0.000000,0.010000,0.010000,21-03-2022,NaN,08:35:00,conditions NaN,NaN,3,Meal,bicycle,1,No,Metropolitian,(min) 22
9499,0x3f0,BANGRES010DEL01,50.0,6.0,12.933298,77.614293,13.003298,77.684293,12-03-2022,NaN,18:25:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Urban,(min) 17
9535,0x3ef,RANCHIRES13DEL01,50.0,6.0,-23.374989,-85.335486,23.444989,85.405486,20-03-2022,NaN,17:55:00,conditions NaN,NaN,3,Snack,bicycle,1,No,Metropolitian,(min) 32
10100,0x5b0,MYSRES04DEL01,50.0,6.0,12.308500,76.665808,12.418500,76.775808,18-03-2022,NaN,20:10:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,(min) 35
10737,0xbffc,DEHRES18DEL02,50.0,6.0,0.000000,0.000000,0.020000,0.020000,13-02-2022,NaN,08:50:00,conditions NaN,NaN,3,Snack,scooter,0,No,Metropolitian,(min) 25
12297,0x940,SURRES02DEL02,50.0,6.0,21.186608,72.794136,21.206608,72.814136,01-03-2022,NaN,11:25:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,(min) 22
13257,0x490,COIMBRES03DEL02,50.0,6.0,11.025083,77.015393,11.105083,77.095393,23-03-2022,NaN,20:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,(min) 11
13652,0x434,RANCHIRES01DEL02,50.0,6.0,-23.416792,-85.316842,23.466792,85.366842,13-03-2022,NaN,20:40:00,conditions NaN,NaN,3,Buffet,motorcycle,0,No,Metropolitian,(min) 28
14106,0x3f6,MYSRES06DEL02,50.0,6.0,12.323994,76.626167,12.373994,76.676167,03-03-2022,NaN,21:25:00,conditions NaN,NaN,3,Meal,scooter,0,No,Urban,(min) 15
14907,0x421,CHENRES19DEL01,50.0,6.0,12.986047,80.218114,12.996047,80.228114,17-03-2022,NaN,09:35:00,conditions NaN,NaN,3,Drinks,bicycle,0,No,Metropolitian,(min) 12
14944,0x43c,HYDRES14DEL01,50.0,6.0,17.426228,78.407495,17.536228,78.517495,02-04-2022,NaN,22:50:00,conditions NaN,NaN,3,Meal,motorcycle,1,No,Urban,(min) 19
16798,0x3fa,RANCHIRES06DEL02,50.0,6.0,23.357804,85.325146,23.377804,85.345146,13-03-2022,NaN,09:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 22
17145,0x400,COIMBRES07DEL01,50.0,6.0,10.961850,76.971082,10.971850,76.981082,05-03-2022,NaN,09:15:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Urban,(min) 14
17708,0x412,CHENRES010DEL01,50.0,6.0,-13.066762,-80.251865,13.076762,80.261865,17-03-2022,NaN,09:15:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,(min) 20
18977,0xc363,BHPRES08DEL03,50.0,6.0,23.232537,77.429845,23.322537,77.519845,18-02-2022,NaN,21:25:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,(min) 17
19382,0x3fb,INDORES02DEL03,50.0,6.0,-22.651847,-75.881991,22.711847,75.941991,05-03-2022,NaN,19:30:00,conditions NaN,NaN,3,Drinks,bicycle,0,No,Metropolitian,(min) 30
20269,0xd0bc,ALHRES01DEL02,50.0,6.0,25.454648,81.834502,25.504648,81.884502,15-02-2022,NaN,21:55:00,conditions NaN,NaN,3,Snack,motorcycle,1,No,Urban,(min) 33
21320,0x810,HYDRES06DEL01,50.0,6.0,17.455894,78.375467,17.525894,78.445467,06-04-2022,NaN,17:30:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,(min) 35
22416,0xc7d6,ALHRES08DEL03,50.0,6.0,25.450329,81.834279,25.590329,81.974279,16-02-2022,NaN,17:45:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,(min) 29
23375,0x1060,BANGRES05DEL03,50.0,6.0,12.970324,77.645748,13.030324,77.705748,09-03-2022,NaN,22:15:00,conditions NaN,NaN,3,Buffet,electric_scooter,0,No,Urban,(min) 19
24237,0x420,SURRES13DEL01,50.0,6.0,-21.170096,-72.789122,21.180096,72.799122,15-03-2022,NaN,10:10:00,conditions NaN,NaN,3,Meal,motorcycle,0,No,Metropolitian,(min) 17
24918,0xbf34,KNPRES16DEL02,50.0,6.0,26.482581,80.315628,26.612581,80.445628,12-02-2022,NaN,18:30:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,(min) 41
25285,0x40c,COIMBRES08DEL03,50.0,6.0,11.001852,76.976268,11.061852,77.036268,01-03-2022,NaN,17:50:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,(min) 16
26052,0x694,RANCHIRES09DEL02,50.0,6.0,23.351058,85.325731,23.371058,85.345731,21-03-2022,NaN,08:40:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,(min) 20
27221,0x3f4,COIMBRES20DEL02,50.0,6.0,-10.994136,-76.963303,11.074136,77.043303,06-03-2022,NaN,17:20:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,NaN,(min) 17
27399,0x3ea,MUMRES20DEL03,50.0,6.0,19.103249,72.846749,19.133249,72.876749,24-03-2022,NaN,23:20:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Metropolitian,(min) 18
28315,0x3fd,BANGRES13DEL01,50.0,6.0,-12.935662,-77.614130,13.045662,77.724130,06-03-2022,NaN,17:30:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,(min) 28
28974,0x404,CHENRES04DEL01,50.0,6.0,-13.029780,-80.208812,13.099780,80.278812,18-03-2022,NaN,23:55:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,(min) 20
29535,0x480,BANGRES15DEL01,50.0,6.0,-12.975377,-77.696664,13.015377,77.736664,01-03-2022,NaN,13:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,(min) 15
30579,0xbf12,BHPRES20DEL03,50.0,6.0,23.235123,77.398886,23.325123,77.488886,16-02-2022,NaN,23:10:00,conditions NaN,NaN,3,Snack,bicycle,2,No,Metropolitian,(min) 39
30943,0x4cc,MUMRES20DEL01,50.0,6.0,-19.103249,-72.846749,19.213249,72.956749,16-03-2022,NaN,22:00:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,(min) 30
31233,0x706,VADRES09DEL02,50.0,6.0,0.000000,0.000000,0.050000,0.050000,11-03-2022,NaN,22:30:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,(min) 28
32326,0xbf33,KNPRES03DEL03,50.0,6.0,-26.469003,-80.316344,26.559003,80.406344,14-02-2022,NaN,22:55:00,conditions NaN,NaN,3,Drinks,scooter,0,No,NaN,(min) 17
33533,0xbf01,KOLRES06DEL02,50.0,6.0,-22.533662,-88.366217,22.663662,88.496217,18-02-2022,NaN,21:50:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,(min) 28
34688,0xbf76,AGRRES20DEL03,50.0,6.0,-27.158822,-78.045359,27.248822,78.135359,14-02-2022,NaN,23:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,(min) 16
38007,0xbef2,DEHRES13DEL01,50.0,6.0,30.366322,78.070453,30.436322,78.140453,14-02-2022,NaN,18:05:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,(min) 25
38020,0x466,CHENRES14DEL02,50.0,6.0,13.026279,80.174568,13.106279,80.254568,20-03-2022,NaN,23:10:00,conditions NaN,NaN,3,Meal,scooter,0,No,Metropolitian,(min) 14
38561,0x3f1,VADRES09DEL03,50.0,6.0,0.000000,0.000000,0.090000,0.090000,06-04-2022,NaN,19:20:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,(min) 36
38649,0x5e0,MUMRES07DEL03,50.0,6.0,-19.091458,72.827808,19.121458,72.857808,11-03-2022,NaN,21:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,(min) 26
39699,0xa24,RANCHIRES14DEL03,50.0,6.0,0.000000,0.000000,0.030000,0.030000,21-03-2022,NaN,21:10:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,(min) 39
40223,0x3e9,MYSRES04DEL03,50.0,6.0,-12.308500,-76.665808,12.398500,76.755808,12-03-2022,NaN,17:45:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,(min) 40
41105,0x4e4,VADRES17DEL01,50.0,6.0,0.000000,0.000000,0.110000,0.110000,20-03-2022,NaN,21:55:00,conditions NaN,NaN,3,Meal,scooter,1,Yes,Metropolitian,(min) 48
41969,0xbef4,KNPRES19DEL03,50.0,6.0,-26.490950,-80.318656,26.520950,80.348656,13-02-2022,NaN,00:00:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 15
42072,0x5fc,INDORES11DEL03,50.0,6.0,22.751234,75.889490,22.781234,75.919490,17-03-2022,NaN,20:40:00,conditions NaN,NaN,3,Buffet,scooter,0,No,Metropolitian,(min) 28
42835,0x53e,BANGRES12DEL01,50.0,6.0,-12.939496,77.625999,12.949496,77.635999,19-03-2022,NaN,09:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,(min) 19
45332,0x2950,VADRES04DEL02,50.0,6.0,0.000000,0.000000,0.020000,0.020000,19-03-2022,NaN,10:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,(min) 28

In [27]:
df['multiple_deliveries'].unique()

array(['0', '1', '3', 'NaN ', '2'], dtype=object)

In [28]:
df['multiple_deliveries'] = pd.to_numeric(
    df['multiple_deliveries'],
    errors='coerce'
)

In [29]:
df['Time_taken(min)'].unique()

array(['(min) 24', '(min) 33', '(min) 26', '(min) 21', '(min) 30',
       '(min) 40', '(min) 32', '(min) 34', '(min) 46', '(min) 23',
       '(min) 20', '(min) 41', '(min) 15', '(min) 36', '(min) 39',
       '(min) 18', '(min) 38', '(min) 47', '(min) 12', '(min) 22',
       '(min) 25', '(min) 35', '(min) 10', '(min) 19', '(min) 11',
       '(min) 28', '(min) 52', '(min) 16', '(min) 27', '(min) 49',
       '(min) 17', '(min) 14', '(min) 37', '(min) 44', '(min) 42',
       '(min) 31', '(min) 13', '(min) 29', '(min) 50', '(min) 43',
       '(min) 48', '(min) 54', '(min) 53', '(min) 45', '(min) 51'],
      dtype=object)

In [30]:
df['Time_taken(min)'] = pd.to_numeric(
    df['Time_taken(min)'],
    errors='coerce'
)

In [31]:
df['Time_taken(min)'].dtype

dtype('float64')

In [32]:
df['Time_taken(min)'].isnull().sum()

np.int64(45593)

In [33]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

/tmp/ipykernel_2328/356155431.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [34]:
df['Time_Orderd'].unique()
df['Time_Order_picked'].unique()

array(['11:45:00', '19:50:00', '08:45:00', '18:10:00', '13:45:00',
       '21:30:00', '19:30:00', '17:30:00', '21:05:00', '22:10:00',
       '15:05:00', '17:40:00', '09:30:00', '20:05:00', '20:35:00',
       '15:10:00', '20:40:00', '20:50:00', '20:25:00', '22:45:00',
       '08:30:00', '19:45:00', '12:30:00', '18:50:00', '23:30:00',
       '21:35:00', '23:45:00', '22:50:00', '22:40:00', '23:35:00',
       '13:40:00', '21:45:00', '19:10:00', '14:25:00', '11:10:00',
       '09:55:00', '08:55:00', '23:10:00', '18:35:00', '19:25:00',
       '11:00:00', '19:15:00', '16:55:00', '11:40:00', '15:15:00',
       '22:55:00', '22:25:00', '20:55:00', '23:05:00', '18:00:00',
       '23:00:00', '09:40:00', '20:20:00', '22:35:00', '22:00:00',
       '23:55:00', '15:40:00', '10:30:00', '21:00:00', '10:50:00',
       '16:05:00', '20:15:00', '12:15:00', '15:45:00', '22:15:00',
       '10:45:00', '15:30:00', '00:05:00', '21:25:00', '12:45:00',
       '21:15:00', '18:20:00', '18:25:00', '11:50:00', '12:50:00',
       '10:55:00', '21:40:00', '10:20:00', '17:55:00', '23:50:00',
       '12:55:00', '00:10:00', '10:40:00', '09:00:00', '20:45:00',
       '20:00:00', '23:15:00', '22:20:00', '17:00:00', '00:15:00',
       '21:20:00', '14:35:00', '10:25:00', '09:05:00', '16:50:00',
       '08:40:00', '23:40:00', '21:50:00', '19:55:00', '15:00:00',
       '10:35:00', '09:25:00', '17:20:00', '17:25:00', '20:10:00',
       '00:00:00', '17:35:00', '19:00:00', '19:05:00', '13:20:00',
       '17:50:00', '18:05:00', '19:20:00', '10:05:00', '09:10:00',
       '21:55:00', '19:40:00', '09:50:00', '15:50:00', '18:30:00',
       '18:15:00', '16:15:00', '11:15:00', '21:10:00', '22:30:00',
       '15:20:00', '18:40:00', '23:20:00', '11:25:00', '13:55:00',
       '18:45:00', '22:05:00', '11:55:00', '18:55:00', '09:45:00',
       '17:15:00', '12:05:00', '12:00:00', '19:35:00', '08:25:00',
       '11:05:00', '15:35:00', '12:40:00', '12:25:00', '08:20:00',
       '23:25:00', '16:10:00', '08:15:00', '20:30:00', '13:00:00',
       '11:20:00', '08:50:00', '14:45:00', '17:45:00', '10:00:00',
       '08:35:00', '12:10:00', '11:35:00', '14:30:00', '10:15:00',
       '17:05:00', '10:10:00', '09:35:00', '11:30:00', '16:25:00',
       '09:15:00', '13:35:00', '15:55:00', '13:10:00', '13:05:00',
       '16:20:00', '16:30:00', '16:45:00', '09:20:00', '13:25:00',
       '14:15:00', '14:05:00', '16:35:00', '16:40:00', '13:30:00',
       '14:40:00', '12:20:00', '13:50:00', '17:10:00', '15:25:00',
       '14:20:00', '12:35:00', '14:00:00', '14:10:00', '14:55:00',
       '13:15:00', '14:50:00', '16:00:00'], dtype=object)

In [35]:
df['Time_Orderd'].unique()

array(['11:30:00', '19:45:00', '08:30:00', '18:00:00', '13:30:00',
       '21:20:00', '19:15:00', '17:25:00', '20:55:00', '21:55:00',
       '14:55:00', '17:30:00', '09:20:00', '19:50:00', '20:25:00',
       '20:30:00', '20:40:00', '21:15:00', '20:20:00', '22:30:00',
       '08:15:00', '19:30:00', '12:25:00', '18:35:00', '20:35:00',
       '23:20:00', '23:35:00', '22:35:00', '23:25:00', '13:35:00',
       '21:35:00', '18:55:00', '14:15:00', '11:00:00', '09:45:00',
       '08:40:00', '23:00:00', 'NaN ', '19:10:00', '10:55:00', '21:40:00',
       '19:00:00', '16:45:00', '15:10:00', '22:45:00', '22:10:00',
       '20:45:00', '22:50:00', '17:55:00', '09:25:00', '20:15:00',
       '22:25:00', '22:40:00', '23:50:00', '15:25:00', '10:20:00',
       '10:40:00', '15:55:00', '20:10:00', '12:10:00', '15:30:00',
       '10:35:00', '21:10:00', '20:50:00', '12:35:00', '21:00:00',
       '23:40:00', '18:15:00', '18:20:00', '11:45:00', '12:45:00',
       '23:30:00', '10:50:00', '21:25:00', '10:10:00', '17:50:00',
       '22:20:00', '12:40:00', '23:55:00', '10:25:00', '08:45:00',
       '23:45:00', '19:55:00', '22:15:00', '23:10:00', '09:15:00',
       '18:25:00', '18:45:00', '16:50:00', '00:00:00', '14:20:00',
       '10:15:00', '08:50:00', '09:00:00', '17:45:00', '16:35:00',
       '21:45:00', '19:40:00', '14:50:00', '18:10:00', '12:20:00',
       '12:50:00', '09:10:00', '12:30:00', '17:10:00', '17:20:00',
       '18:30:00', '13:10:00', '19:35:00', '09:50:00', '15:00:00',
       '20:00:00', '10:30:00', '09:40:00', '15:35:00', '16:55:00',
       '22:55:00', '16:00:00', '17:15:00', '21:30:00', '18:40:00',
       '11:10:00', '13:50:00', '10:00:00', '21:50:00', '11:50:00',
       '22:00:00', '08:25:00', '11:20:00', '11:55:00', '09:30:00',
       '08:20:00', '08:10:00', '11:40:00', '23:15:00', '19:20:00',
       '12:15:00', '11:35:00', '11:15:00', '17:35:00', '17:40:00',
       '14:40:00', '18:50:00', '11:25:00', '14:25:00', '12:00:00',
       '16:10:00', '19:25:00', '08:55:00', '13:40:00', '17:00:00',
       '09:35:00', '08:35:00', '16:15:00', '13:20:00', '15:50:00',
       '15:20:00', '16:20:00', '14:30:00', '15:45:00', '16:40:00',
       '13:00:00', '12:55:00', '10:45:00', '13:25:00', '09:55:00',
       '15:15:00', '13:15:00', '14:00:00', '15:40:00', '16:25:00',
       '14:10:00', '13:45:00', '13:55:00', '14:35:00', '16:30:00',
       '14:45:00'], dtype=object)

In [36]:
df['Time_Order_picked'].unique()

array(['11:45:00', '19:50:00', '08:45:00', '18:10:00', '13:45:00',
       '21:30:00', '19:30:00', '17:30:00', '21:05:00', '22:10:00',
       '15:05:00', '17:40:00', '09:30:00', '20:05:00', '20:35:00',
       '15:10:00', '20:40:00', '20:50:00', '20:25:00', '22:45:00',
       '08:30:00', '19:45:00', '12:30:00', '18:50:00', '23:30:00',
       '21:35:00', '23:45:00', '22:50:00', '22:40:00', '23:35:00',
       '13:40:00', '21:45:00', '19:10:00', '14:25:00', '11:10:00',
       '09:55:00', '08:55:00', '23:10:00', '18:35:00', '19:25:00',
       '11:00:00', '19:15:00', '16:55:00', '11:40:00', '15:15:00',
       '22:55:00', '22:25:00', '20:55:00', '23:05:00', '18:00:00',
       '23:00:00', '09:40:00', '20:20:00', '22:35:00', '22:00:00',
       '23:55:00', '15:40:00', '10:30:00', '21:00:00', '10:50:00',
       '16:05:00', '20:15:00', '12:15:00', '15:45:00', '22:15:00',
       '10:45:00', '15:30:00', '00:05:00', '21:25:00', '12:45:00',
       '21:15:00', '18:20:00', '18:25:00', '11:50:00', '12:50:00',
       '10:55:00', '21:40:00', '10:20:00', '17:55:00', '23:50:00',
       '12:55:00', '00:10:00', '10:40:00', '09:00:00', '20:45:00',
       '20:00:00', '23:15:00', '22:20:00', '17:00:00', '00:15:00',
       '21:20:00', '14:35:00', '10:25:00', '09:05:00', '16:50:00',
       '08:40:00', '23:40:00', '21:50:00', '19:55:00', '15:00:00',
       '10:35:00', '09:25:00', '17:20:00', '17:25:00', '20:10:00',
       '00:00:00', '17:35:00', '19:00:00', '19:05:00', '13:20:00',
       '17:50:00', '18:05:00', '19:20:00', '10:05:00', '09:10:00',
       '21:55:00', '19:40:00', '09:50:00', '15:50:00', '18:30:00',
       '18:15:00', '16:15:00', '11:15:00', '21:10:00', '22:30:00',
       '15:20:00', '18:40:00', '23:20:00', '11:25:00', '13:55:00',
       '18:45:00', '22:05:00', '11:55:00', '18:55:00', '09:45:00',
       '17:15:00', '12:05:00', '12:00:00', '19:35:00', '08:25:00',
       '11:05:00', '15:35:00', '12:40:00', '12:25:00', '08:20:00',
       '23:25:00', '16:10:00', '08:15:00', '20:30:00', '13:00:00',
       '11:20:00', '08:50:00', '14:45:00', '17:45:00', '10:00:00',
       '08:35:00', '12:10:00', '11:35:00', '14:30:00', '10:15:00',
       '17:05:00', '10:10:00', '09:35:00', '11:30:00', '16:25:00',
       '09:15:00', '13:35:00', '15:55:00', '13:10:00', '13:05:00',
       '16:20:00', '16:30:00', '16:45:00', '09:20:00', '13:25:00',
       '14:15:00', '14:05:00', '16:35:00', '16:40:00', '13:30:00',
       '14:40:00', '12:20:00', '13:50:00', '17:10:00', '15:25:00',
       '14:20:00', '12:35:00', '14:00:00', '14:10:00', '14:55:00',
       '13:15:00', '14:50:00', '16:00:00'], dtype=object)

In [37]:
df['Time_Orderd'].head(10)

0    11:30:00
1    19:45:00
2    08:30:00
3    18:00:00
4    13:30:00
5    21:20:00
6    19:15:00
7    17:25:00
8    20:55:00
9    21:55:00
Name: Time_Orderd, dtype: object

In [38]:
df['Time_Orderd'] = pd.to_datetime(
    df['Time_Orderd'], format='%H:%M:%S', errors='coerce'
).dt.time

df['Time_Order_picked'] = pd.to_datetime(
    df['Time_Order_picked'], format='%H:%M:%S', errors='coerce'
).dt.time

In [39]:
df['Time_Orderd'].dtype

dtype('O')

In [40]:
df[['Time_Orderd', 'Time_Order_picked']].head(10)

  Time_Orderd Time_Order_picked
0    11:30:00          11:45:00
1    19:45:00          19:50:00
2    08:30:00          08:45:00
3    18:00:00          18:10:00
4    13:30:00          13:45:00
5    21:20:00          21:30:00
6    19:15:00          19:30:00
7    17:25:00          17:30:00
8    20:55:00          21:05:00
9    21:55:00          22:10:00

In [41]:
df['Time_Orderd'] = pd.to_datetime(
    df['Time_Orderd'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

In [42]:
df['Time_Order_picked'] = pd.to_datetime(
    df['Time_Order_picked'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

In [43]:
df[['Time_Orderd', 'Time_Order_picked']].head()

  Time_Orderd Time_Order_picked
0    11:30:00          11:45:00
1    19:45:00          19:50:00
2    08:30:00          08:45:00
3    18:00:00          18:10:00
4    13:30:00          13:45:00

In [44]:
df['Order_Date'].head()

0   2022-03-19
1   2022-03-25
2   2022-03-19
3   2022-04-05
4   2022-03-26
Name: Order_Date, dtype: datetime64[ns]

In [45]:
print("===== DATA TYPES =====")
print(df.dtypes)

print("\n===== NULL VALUES =====")
print(df.isnull().sum())

print("\n===== DUPLICATES =====")
print(df.duplicated().sum())

print("\n===== RATINGS ABOVE 5 =====")
print(df[df['Delivery_person_Ratings'] > 5])

===== DATA TYPES =====
ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                   float64
Festival                               object
City                                   object
Time_taken(min)                       float64
dtype: object

===== NULL VALUES =====
ID                                 0
Delivery_person_ID                 0
Delivery_person_Age             1854
Delivery_person_Ratings         1908
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                     1731
Time_Order_picked                  0
Weatherconditions                  0
Road_traffic_density               0
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries              993
Festival                           0
City                               0
Time_taken(min)                45593
dtype: int64

===== DUPLICATES =====
0

===== RATINGS ABOVE 5 =====
            ID Delivery_person_ID  Delivery_person_Age  \
3586    0x46d     BANGRES05DEL01                  50.0
4714    0x493      HYDRES17DEL01                  50.0
5169    0x4f2      JAPRES08DEL01                  50.0
5362    0x430     BANGRES19DEL01                  50.0
5651   0xbef1      AGRRES13DEL02                  50.0
6394    0x427      JAPRES06DEL02                  50.0
7031    0x3eb      MYSRES15DEL02                  50.0
7681    0xd42      VADRES09DEL01                  50.0
9499    0x3f0    BANGRES010DEL01                  50.0
9535    0x3ef   RANCHIRES13DEL01                  50.0
10100   0x5b0      MYSRES04DEL01                  50.0
10737  0xbffc      DEHRES18DEL02                  50.0
12297   0x940      SURRES02DEL02                  50.0
13257   0x490    COIMBRES03DEL02                  50.0
13652   0x434   RANCHIRES01DEL02                  50.0
14106   0x3f6      MYSRES06DEL02                  50.0
14907   0x421     CHENRES19DEL01                  50.0
14944   0x43c      HYDRES14DEL01                  50.0
16798   0x3fa   RANCHIRES06DEL02                  50.0
17145   0x400    COIMBRES07DEL01                  50.0
17708   0x412    CHENRES010DEL01                  50.0
18977  0xc363      BHPRES08DEL03                  50.0
19382   0x3fb     INDORES02DEL03                  50.0
20269  0xd0bc      ALHRES01DEL02                  50.0
21320   0x810      HYDRES06DEL01                  50.0
22416  0xc7d6      ALHRES08DEL03                  50.0
23375  0x1060     BANGRES05DEL03                  50.0
24237   0x420      SURRES13DEL01                  50.0
24918  0xbf34      KNPRES16DEL02                  50.0
25285   0x40c    COIMBRES08DEL03                  50.0
26052   0x694   RANCHIRES09DEL02                  50.0
27221   0x3f4    COIMBRES20DEL02                  50.0
27399   0x3ea      MUMRES20DEL03                  50.0
28315   0x3fd     BANGRES13DEL01                  50.0
28974   0x404     CHENRES04DEL01                  50.0
29535   0x480     BANGRES15DEL01                  50.0
30579  0xbf12      BHPRES20DEL03                  50.0
30943   0x4cc      MUMRES20DEL01                  50.0
31233   0x706      VADRES09DEL02                  50.0
32326  0xbf33      KNPRES03DEL03                  50.0
33533  0xbf01      KOLRES06DEL02                  50.0
34688  0xbf76      AGRRES20DEL03                  50.0
38007  0xbef2      DEHRES13DEL01                  50.0
38020   0x466     CHENRES14DEL02                  50.0
38561   0x3f1      VADRES09DEL03                  50.0
38649   0x5e0      MUMRES07DEL03                  50.0
39699   0xa24   RANCHIRES14DEL03                  50.0
40223   0x3e9      MYSRES04DEL03                  50.0
41105   0x4e4      VADRES17DEL01                  50.0
41969  0xbef4      KNPRES19DEL03                  50.0
42072   0x5fc     INDORES11DEL03                  50.0
42835   0x53e     BANGRES12DEL01                  50.0
45332  0x2950      VADRES04DEL02                  50.0

       Delivery_person_Ratings  Restaurant_latitude  Restaurant_longitude  \
3586                       6.0           -12.970324            -77.645748
4714                       6.0           -17.451976            -78.385883
5169                       6.0           -26.910262            -75.783013
5362                       6.0            12.914264             77.678400
5651                       6.0           -27.159795            -78.042990
6394                       6.0            26.911927             75.797282
7031                       6.0           -12.352058            -76.606650
7681                       6.0             0.000000              0.000000
9499                       6.0            12.933298             77.614293
9535                       6.0           -23.374989            -85.335486
10100                      6.0            12.308500             76.665808
10737                      6.0             0.000000              0.000000
12297                      6.0            21.186608             72.794136
13257                      6.0            11.025083             77.015393
13652                      6.0           -23.416792            -85.316842
14106                      6.0            12.323994             76.626167
14907                      6.0            12.986047             80.218114
14944                      6.0            17.426228             78.407495
16798                      6.0            23.357804             85.325146
17145                      6.0            10.961850             76.971082
17708                      6.0           -13.066762            -80.251865
18977                      6.0            23.232537             77.429845
19382                      6.0           -22.651847            -75.881991
20269                      6.0            25.454648             81.834502
21320                      6.0            17.455894             78.375467
22416                      6.0            25.450329             81.834279
23375                      6.0            12.970324             77.645748
24237                      6.0           -21.170096            -72.789122
24918                      6.0            26.482581             80.315628
25285                      6.0            11.001852             76.976268
26052                      6.0            23.351058             85.325731
27221                      6.0           -10.994136            -76.963303
27399                      6.0            19.103249             72.846749
28315                      6.0           -12.935662            -77.614130
28974                      6.0           -13.029780            -80.208812
29535                      6.0           -12.975377            -77.696664
30579                      6.0            23.235123             77.398886
30943                      6.0           -19.103249            -72.846749
31233                      6.0             0.000000              0.000000
32326                      6.0           -26.469003            -80.316344
33533                      6.0           -22.533662            -88.366217
34688                      6.0           -27.158822            -78.045359
38007                      6.0            30.366322             78.070453
38020                      6.0            13.026279             80.174568
38561                      6.0             0.000000              0.000000
38649                      6.0           -19.091458             72.827808
39699                      6.0             0.000000              0.000000
40223                      6.0           -12.308500            -76.665808
41105                      6.0             0.000000              0.000000
41969                      6.0           -26.490950            -80.318656
42072                      6.0            22.751234             75.889490
42835                      6.0           -12.939496             77.625999
45332                      6.0             0.000000              0.000000

       Delivery_location_latitude  Delivery_location_longitude Order_Date  \
3586                    13.010324                    77.685748 2022-03-13
4714                    17.561976                    78.495883 2022-04-04
5169                    27.020262                    75.893013 2022-03-18
5362                    13.024264                    77.788400 2022-04-06
5651                    27.209795                    78.092990 2022-02-13
6394                    27.041927                    75.927282 2022-04-02
7031                    12.372058                    76.626650 2022-03-15
7681                     0.010000                     0.010000 2022-03-21
9499                    13.003298                    77.684293 2022-03-12
9535                    23.444989                    85.405486 2022-03-20
10100                   12.418500                    76.775808 2022-03-18
10737                    0.020000                     0.020000 2022-02-13
12297                   21.206608                    72.814136 2022-03-01
13257                   11.105083                    77.095393 2022-03-23
13652                   23.466792                    85.366842 2022-03-13
14106                   12.373994                    76.676167 2022-03-03
14907                   12.996047                    80.228114 2022-03-17
14944                   17.536228                    78.517495 2022-04-02
16798                   23.377804                    85.345146 2022-03-13
17145                   10.971850                    76.981082 2022-03-05
17708                   13.076762                    80.261865 2022-03-17
18977                   23.322537                    77.519845 2022-02-18
19382                   22.711847                    75.941991 2022-03-05
20269                   25.504648                    81.884502 2022-02-15
21320                   17.525894                    78.445467 2022-04-06
22416                   25.590329                    81.974279 2022-02-16
23375                   13.030324                    77.705748 2022-03-09
24237                   21.180096                    72.799122 2022-03-15
24918                   26.612581                    80.445628 2022-02-12
25285                   11.061852                    77.036268 2022-03-01
26052                   23.371058                    85.345731 2022-03-21
27221                   11.074136                    77.043303 2022-03-06
27399                   19.133249                    72.876749 2022-03-24
28315                   13.045662                    77.724130 2022-03-06
28974                   13.099780                    80.278812 2022-03-18
29535                   13.015377                    77.736664 2022-03-01
30579                   23.325123                    77.488886 2022-02-16
30943                   19.213249                    72.956749 2022-03-16
31233                    0.050000                     0.050000 2022-03-11
32326                   26.559003                    80.406344 2022-02-14
33533                   22.663662                    88.496217 2022-02-18
34688                   27.248822                    78.135359 2022-02-14
38007                   30.436322                    78.140453 2022-02-14
38020                   13.106279                    80.254568 2022-03-20
38561                    0.090000                     0.090000 2022-04-06
38649                   19.121458                    72.857808 2022-03-11
39699                    0.030000                     0.030000 2022-03-21
40223                   12.398500                    76.755808 2022-03-12
41105                    0.110000                     0.110000 2022-03-20
41969                   26.520950                    80.348656 2022-02-13
42072                   22.781234                    75.919490 2022-03-17
42835                   12.949496                    77.635999 2022-03-19
45332                    0.020000                     0.020000 2022-03-19

      Time_Orderd Time_Order_picked Weatherconditions Road_traffic_density  \
3586          NaT          12:30:00    conditions NaN                 NaN
4714          NaT          23:20:00    conditions NaN                 NaN
5169          NaT          18:50:00    conditions NaN                 NaN
5362          NaT          20:55:00    conditions NaN                 NaN
5651          NaT          18:05:00    conditions NaN                 NaN
6394          NaT          22:10:00    conditions NaN                 NaN
7031          NaT          10:00:00    conditions NaN                 NaN
7681          NaT          08:35:00    conditions NaN                 NaN
9499          NaT          18:25:00    conditions NaN                 NaN
9535          NaT          17:55:00    conditions NaN                 NaN
10100         NaT          20:10:00    conditions NaN                 NaN
10737         NaT          08:50:00    conditions NaN                 NaN
12297         NaT          11:25:00    conditions NaN                 NaN
13257         NaT          20:50:00    conditions NaN                 NaN
13652         NaT          20:40:00    conditions NaN                 NaN
14106         NaT          21:25:00    conditions NaN                 NaN
14907         NaT          09:35:00    conditions NaN                 NaN
14944         NaT          22:50:00    conditions NaN                 NaN
16798         NaT          09:05:00    conditions NaN                 NaN
17145         NaT          09:15:00    conditions NaN                 NaN
17708         NaT          09:15:00    conditions NaN                 NaN
18977         NaT          21:25:00    conditions NaN                 NaN
19382         NaT          19:30:00    conditions NaN                 NaN
20269         NaT          21:55:00    conditions NaN                 NaN
21320         NaT          17:30:00    conditions NaN                 NaN
22416         NaT          17:45:00    conditions NaN                 NaN
23375         NaT          22:15:00    conditions NaN                 NaN
24237         NaT          10:10:00    conditions NaN                 NaN
24918         NaT          18:30:00    conditions NaN                 NaN
25285         NaT          17:50:00    conditions NaN                 NaN
26052         NaT          08:40:00    conditions NaN                 NaN
27221         NaT          17:20:00    conditions NaN                 NaN
27399         NaT          23:20:00    conditions NaN                 NaN
28315         NaT          17:30:00    conditions NaN                 NaN
28974         NaT          23:55:00    conditions NaN                 NaN
29535         NaT          13:55:00    conditions NaN                 NaN
30579         NaT          23:10:00    conditions NaN                 NaN
30943         NaT          22:00:00    conditions NaN                 NaN
31233         NaT          22:30:00    conditions NaN                 NaN
32326         NaT          22:55:00    conditions NaN                 NaN
33533         NaT          21:50:00    conditions NaN                 NaN
34688         NaT          23:55:00    conditions NaN                 NaN
38007         NaT          18:05:00    conditions NaN                 NaN
38020         NaT          23:10:00    conditions NaN                 NaN
38561         NaT          19:20:00    conditions NaN                 NaN
38649         NaT          21:50:00    conditions NaN                 NaN
39699         NaT          21:10:00    conditions NaN                 NaN
40223         NaT          17:45:00    conditions NaN                 NaN
41105         NaT          21:55:00    conditions NaN                 NaN
41969         NaT          00:00:00    conditions NaN                 NaN
42072         NaT          20:40:00    conditions NaN                 NaN
42835         NaT          09:40:00    conditions NaN                 NaN
45332         NaT          10:40:00    conditions NaN                 NaN

       Vehicle_condition Type_of_order    Type_of_vehicle  \
3586                   3         Meal   electric_scooter
4714                   3        Snack            bicycle
5169                   3       Drinks            scooter
5362                   3         Meal   electric_scooter
5651                   3       Drinks            scooter
6394                   3         Meal   electric_scooter
7031                   3       Buffet            scooter
7681                   3         Meal            bicycle
9499                   3       Drinks            scooter
9535                   3        Snack            bicycle
10100                  3        Snack   electric_scooter
10737                  3        Snack            scooter
12297                  3         Meal            scooter
13257                  3       Buffet   electric_scooter
13652                  3       Buffet         motorcycle
14106                  3         Meal            scooter
14907                  3       Drinks            bicycle
14944                  3         Meal         motorcycle
16798                  3       Drinks            scooter
17145                  3        Snack   electric_scooter
17708                  3       Drinks   electric_scooter
18977                  3       Buffet            scooter
19382                  3       Drinks            bicycle
20269                  3        Snack         motorcycle
21320                  3       Drinks   electric_scooter
22416                  3       Drinks            scooter
23375                  3       Buffet   electric_scooter
24237                  3         Meal         motorcycle
24918                  3       Buffet            scooter
25285                  3         Meal   electric_scooter
26052                  3         Meal   electric_scooter
27221                  3       Drinks   electric_scooter
27399                  3         Meal   electric_scooter
28315                  3       Drinks   electric_scooter
28974                  3         Meal   electric_scooter
29535                  3       Drinks   electric_scooter
30579                  3        Snack            bicycle
30943                  3         Meal            scooter
31233                  3       Drinks            scooter
32326                  3       Drinks            scooter
33533                  3        Snack            scooter
34688                  3       Drinks   electric_scooter
38007                  3        Snack   electric_scooter
38020                  3         Meal            scooter
38561                  3       Drinks   electric_scooter
38649                  3       Buffet   electric_scooter
39699                  3       Buffet            bicycle
40223                  3       Drinks   electric_scooter
41105                  3         Meal            scooter
41969                  3       Drinks            scooter
42072                  3       Buffet            scooter
42835                  3       Drinks   electric_scooter
45332                  3       Drinks   electric_scooter

       multiple_deliveries Festival            City  Time_taken(min)
3586                   0.0      No           Urban               NaN

In [46]:
print("Total rows:", len(df))
print("Missing Time_taken:", df['Time_taken(min)'].isnull().sum())
print("Percentage missing:",
      df['Time_taken(min)'].isnull().mean() * 100)

Total rows: 45593
Missing Time_taken: 45593
Percentage missing: 100.0

In [47]:
import pandas as pd

# 1. Reload the ORIGINAL train.csv
df = pd.read_csv('/content/train.csv')

# 2. Remove extra spaces from column names
df.columns = df.columns.str.strip()

# 3. Clean whitespace from all text columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

# 4. Convert fake missing values to real NaN
df = df.replace(['NaN', 'nan', 'NaN '], pd.NA)

# 5. Numeric columns
numeric_cols = [
    'Delivery_person_Age',
    'Delivery_person_Ratings',
    'multiple_deliveries'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 6. FIX Time_taken(min)
# Values are like "(min) 24", so remove "(min)"
df['Time_taken(min)'] = (
    df['Time_taken(min)']
    .astype('string')
    .str.replace('(min)', '', regex=False)
    .str.strip()
)

df['Time_taken(min)'] = pd.to_numeric(
    df['Time_taken(min)'],
    errors='coerce'
)

# 7. Convert date
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    errors='coerce'
)

# 8. Convert order times
for col in ['Time_Orderd', 'Time_Order_picked']:
    df[col] = pd.to_datetime(
        df[col],
        format='%H:%M:%S',
        errors='coerce'
    ).dt.time

# 9. Ratings should be between 1 and 5
df.loc[
    (df['Delivery_person_Ratings'] < 1) |
    (df['Delivery_person_Ratings'] > 5),
    'Delivery_person_Ratings'
] = pd.NA

# 10. Check duplicates
df = df.drop_duplicates()

# 11. Final validation
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nTime Taken sample:")
print(df['Time_taken(min)'].head(10))

print("\nRating values:")
print(sorted(df['Delivery_person_Ratings'].dropna().unique()))

/tmp/ipykernel_2328/1215115346.py:41: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(

Shape: (45593, 20)

Data Types:
ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                   float64
Festival                               object
City                                   object
Time_taken(min)                         Int64
dtype: object

Missing Values:
ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1961
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken(min)                   0
dtype: int64

Duplicate Rows: 0

Time Taken sample:
0    24
1    33
2    26
3    21
4    30
5    26
6    40
7    32
8    34
9    46
Name: Time_taken(min), dtype: Int64

Rating values:
[np.float64(1.0), np.float64(2.5), np.float64(2.6), np.float64(2.7), np.float64(2.8), np.float64(2.9), np.float64(3.0), np.float64(3.1), np.float64(3.2), np.float64(3.3), np.float64(3.4), np.float64(3.5), np.float64(3.6), np.float64(3.7), np.float64(3.8), np.float64(3.9), np.float64(4.0), np.float64(4.1), np.float64(4.2), np.float64(4.3), np.float64(4.4), np.float64(4.5), np.float64(4.6), np.float64(4.7), np.float64(4.8), np.float64(4.9), np.float64(5.0)]

In [48]:
import pandas as pd

# ==========================================
# 1. LOAD ORIGINAL DATA
# ==========================================
df = pd.read_csv('/content/train.csv')

# Clean column names
df.columns = df.columns.str.strip()

# Remove leading/trailing spaces from text columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

# Convert common fake missing values to actual NaN
df = df.replace(['NaN', 'nan', ''], pd.NA)


# ==========================================
# 2. NUMERIC COLUMNS
# ==========================================
numeric_cols = [
    'Delivery_person_Age',
    'Delivery_person_Ratings',
    'multiple_deliveries'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')


# ==========================================
# 3. DELIVERY TIME
# ==========================================
# Original values look like "(min) 24"
df['Time_taken(min)'] = (
    df['Time_taken(min)']
    .astype('string')
    .str.replace('(min)', '', regex=False)
    .str.strip()
)

df['Time_taken(min)'] = pd.to_numeric(
    df['Time_taken(min)'],
    errors='coerce'
)


# ==========================================
# 4. DATE
# ==========================================
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)


# ==========================================
# 5. TIME COLUMNS
# ==========================================
for col in ['Time_Orderd', 'Time_Order_picked']:
    df[col] = pd.to_datetime(
        df[col],
        format='%H:%M:%S',
        errors='coerce'
    ).dt.time


# ==========================================
# 6. INVALID RATINGS
# ==========================================
# Valid rating range = 1 to 5
df.loc[
    (df['Delivery_person_Ratings'] < 1) |
    (df['Delivery_person_Ratings'] > 5),
    'Delivery_person_Ratings'
] = pd.NA


# ==========================================
# 7. HANDLE MISSING CATEGORICAL VALUES
# ==========================================
categorical_cols = [
    'Weatherconditions',
    'Road_traffic_density',
    'Festival',
    'City'
]

for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')


# ==========================================
# 8. HANDLE MISSING NUMERIC VALUES
# ==========================================
# Median is less affected by extreme values than mean
for col in [
    'Delivery_person_Age',
    'Delivery_person_Ratings',
    'multiple_deliveries'
]:
    df[col] = df[col].fillna(df[col].median())


# ==========================================
# 9. MISSING ORDER TIME
# ==========================================
df['Time_Orderd'] = df['Time_Orderd'].fillna(
    df['Time_Order_picked']
)


# ==========================================
# 10. REMOVE DUPLICATES
# ==========================================
df = df.drop_duplicates()


# ==========================================
# 11. FINAL VALIDATION
# ==========================================
print("========== FINAL DATASET ==========")
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\n========== MISSING VALUES ==========")
print(df.isnull().sum())

print("\n========== DUPLICATES ==========")
print(df.duplicated().sum())

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== RATING RANGE ==========")
print(df['Delivery_person_Ratings'].min(),
      "to",
      df['Delivery_person_Ratings'].max())

print("\n========== DELIVERY TIME ==========")
print(df['Time_taken(min)'].min(),
      "to",
      df['Time_taken(min)'].max())


# ==========================================
# 12. EXPORT CLEAN DATA
# ==========================================
df.to_csv('/content/cleaned_train.csv', index=False)

print("\n✅ cleaned_train.csv created successfully!")

========== FINAL DATASET ==========
Rows: 45593
Columns: 20

========== MISSING VALUES ==========
ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

========== DUPLICATES ==========
0

========== DATA TYPES ==========
ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                   float64
Festival                               object
City                                   object
Time_taken(min)                         Int64
dtype: object

========== RATING RANGE ==========
1.0 to 5.0

========== DELIVERY TIME ==========
10 to 54

✅ cleaned_train.csv created successfully!